#!/usr/bin/env python3

import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile word")

    # instantiate analyzer
    analyzer = Analyzer()
    # analyze word
    screen_name = sys.argv[1]
    
    tweet = helpers.get_user_timeline(screen_name,50)
    for tweety in tweet:
        score = analyzer.analyze(tweety)
        if score > 0.0:
            print(colored(score, "green"), colored(tweety, "green"))
        elif score < 0.0:
            print(colored(score, "red"), colored(tweety, "red"))
        else:
            print(colored(score, "yellow"), colored(tweety, "yellow"))

if __name__ == "__main__":
    main()
